# import tabula

# df = tabula.read_pdf("aaa.pdf", pages=1)[0]
# df.to_excel("bbb.xlsx")


jinay = [
    [
        {"0 cc": "DCSC301"},
        {"1 subj": "Applied Mathematics-III"},
        {"2  highest": "100"},
        {"3 course credits": "5"},
        {"4 tt highest": "25"},
        {"5 tt marks": "21"},
        {"6 sem highest": "75"},
        {"7 sem marks": "66"},
        {"8 final max": "100"},
        {"9 marks obtained": "87"},
        {"10 grade": "O"},
        {"11 credits": "5"},
        {"12 grade points": "10"},
        {"13 credits*grade": "50"},
        {"14 ptr": "9.08"},
    ],
    [
        {"0 cc": "DCSC302"},
        {"1 subj": "Digital Logic Design and Analysis"},
        {"2  highest": "97"},
        {"3 course credits": "4"},
        {"4 tt highest": "25"},
        {"5 tt marks": "18"},
        {"6 sem highest": "75"},
        {"7 sem marks": "51"},
        {"8 final max": "100"},
        {"9 marks obtained": "69"},
        {"10 grade": "C"},
        {"11 credits": "4"},
        {"12 grade points": "7"},
        {"13 credits*grade": "28"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "DCSL302"},
        {"1 subj": "Digital Logic Design and Analysis Laboratory"},
        {"2  highest": "47"},
        {"3 course credits": "1"},
        {"4 tt highest": "25"},
        {"5 tt marks": "22"},
        {"6 sem highest": "25"},
        {"7 sem marks": "23"},
        {"8 final max": "50"},
        {"9 marks obtained": "45"},
        {"10 grade": "O"},
        {"11 credits": "1"},
        {"12 grade points": "10"},
        {"13 credits*grade": "10"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "DCSC303"},
        {"1 subj": "Discrete Mathematics"},
        {"2  highest": "100"},
        {"3 course credits": "4"},
        {"4 tt highest": "25"},
        {"5 tt marks": "22"},
        {"6 sem highest": "75"},
        {"7 sem marks": "72"},
        {"8 final max": "100"},
        {"9 marks obtained": "94"},
        {"10 grade": "O"},
        {"11 credits": "4"},
        {"12 grade points": "10"},
        {"13 credits*grade": "40"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "DCSC304"},
        {"1 subj": "Electronic Circuits and Communication\rFundamentals"},
        {"2  highest": "99"},
        {"3 course credits": "4"},
        {"4 tt highest": "25"},
        {"5 tt marks": "21"},
        {"6 sem highest": "75"},
        {"7 sem marks": "45"},
        {"8 final max": "100"},
        {"9 marks obtained": "66"},
        {"10 grade": "C"},
        {"11 credits": "4"},
        {"12 grade points": "7"},
        {"13 credits*grade": "28"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "DCSL304"},
        {"1 subj": "Electronics Circuits and Communication\rFundamentals Laboratory"},
        {"2  highest": "49"},
        {"3 course credits": "1"},
        {"4 tt highest": "25"},
        {"5 tt marks": "24"},
        {"6 sem highest": "25"},
        {"7 sem marks": "23"},
        {"8 final max": "50"},
        {"9 marks obtained": "47"},
        {"10 grade": "O"},
        {"11 credits": "1"},
        {"12 grade points": "10"},
        {"13 credits*grade": "10"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "DCSC305"},
        {"1 subj": "Data Structures"},
        {"2  highest": "98"},
        {"3 course credits": "4"},
        {"4 tt highest": "25"},
        {"5 tt marks": "21"},
        {"6 sem highest": "75"},
        {"7 sem marks": "69"},
        {"8 final max": "100"},
        {"9 marks obtained": "90"},
        {"10 grade": "O"},
        {"11 credits": "4"},
        {"12 grade points": "10"},
        {"13 credits*grade": "40"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "DCSL305"},
        {"1 subj": "Data Structures Laboratory"},
        {"2  highest": "47"},
        {"3 course credits": "1"},
        {"4 tt highest": "25"},
        {"5 tt marks": "23"},
        {"6 sem highest": "25"},
        {"7 sem marks": "24"},
        {"8 final max": "50"},
        {"9 marks obtained": "47"},
        {"10 grade": "O"},
        {"11 credits": "1"},
        {"12 grade points": "10"},
        {"13 credits*grade": "10"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "DCSL306"},
        {"1 subj": "Object Oriented Programming Methodology\rLaboratory"},
        {"2  highest": "96"},
        {"3 course credits": "2"},
        {"4 tt highest": "50"},
        {"5 tt marks": "48"},
        {"6 sem highest": "50"},
        {"7 sem marks": "46"},
        {"8 final max": "100"},
        {"9 marks obtained": "94"},
        {"10 grade": "O"},
        {"11 credits": "2"},
        {"12 grade points": "10"},
        {"13 credits*grade": "20"},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "Total"},
        {"1 subj": ""},
        {"2  highest": "26"},
        {"3 course credits": ""},
        {"4 tt highest": ""},
        {"5 tt marks": ""},
        {"6 sem highest": ""},
        {"7 sem marks": ""},
        {"8 final max": ""},
        {"9 marks obtained": ""},
        {"10 grade": "26"},
        {"11 credits": ""},
        {"12 grade points": "236"},
        {"13 credits*grade": ""},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": "Remark : SuccessfulCredits Earned :26SGPA :9.08"},
        {"1 subj": ""},
        {"2  highest": ""},
        {"3 course credits": ""},
        {"4 tt highest": ""},
        {"5 tt marks": ""},
        {"6 sem highest": ""},
        {"7 sem marks": ""},
        {"8 final max": ""},
        {"9 marks obtained": ""},
        {"10 grade": ""},
        {"11 credits": ""},
        {"12 grade points": ""},
        {"13 credits*grade": ""},
        {"14 ptr": ""},
    ],
    [
        {"0 cc": ""},
        {"1 subj": ""},
        {"2  highest": ""},
        {"3 course credits": ""},
        {"4 tt highest": ""},
        {"5 tt marks": ""},
        {"6 sem highest": ""},
        {"7 sem marks": ""},
        {"8 final max": ""},
        {"9 marks obtained": ""},
        {"10 grade": ""},
        {"11 credits": ""},
        {"12 grade points": ""},
        {"13 credits*grade": ""},
        {"14 ptr": ""},
    ],
]
sem1 = {}

for i in jinay:
    subj = {}
    for j in i:
        subj.update(j)
    sem1[subj["0 cc"]] = subj
print(sem1)


{
    "DCSC301": {
        "0 cc": "DCSC301",
        "1 subj": "Applied Mathematics-III",
        "2  highest": "100",
        "3 course credits": "5",
        "4 tt highest": "25",
        "5 tt marks": "21",
        "6 sem highest": "75",
        "7 sem marks": "66",
        "8 final max": "100",
        "9 marks obtained": "87",
        "10 grade": "O",
        "11 credits": "5",
        "12 grade points": "10",
        "13 credits*grade": "50",
        "14 ptr": "9.08",
    },
    "DCSC302": {
        "0 cc": "DCSC302",
        "1 subj": "Digital Logic Design and Analysis",
        "2  highest": "97",
        "3 course credits": "4",
        "4 tt highest": "25",
        "5 tt marks": "18",
        "6 sem highest": "75",
        "7 sem marks": "51",
        "8 final max": "100",
        "9 marks obtained": "69",
        "10 grade": "C",
        "11 credits": "4",
        "12 grade points": "7",
        "13 credits*grade": "28",
        "14 ptr": "",
    },
    "DCSL302": {
        "0 cc": "DCSL302",
        "1 subj": "Digital Logic Design and Analysis Laboratory",
        "2  highest": "47",
        "3 course credits": "1",
        "4 tt highest": "25",
        "5 tt marks": "22",
        "6 sem highest": "25",
        "7 sem marks": "23",
        "8 final max": "50",
        "9 marks obtained": "45",
        "10 grade": "O",
        "11 credits": "1",
        "12 grade points": "10",
        "13 credits*grade": "10",
        "14 ptr": "",
    },
    "DCSC303": {
        "0 cc": "DCSC303",
        "1 subj": "Discrete Mathematics",
        "2  highest": "100",
        "3 course credits": "4",
        "4 tt highest": "25",
        "5 tt marks": "22",
        "6 sem highest": "75",
        "7 sem marks": "72",
        "8 final max": "100",
        "9 marks obtained": "94",
        "10 grade": "O",
        "11 credits": "4",
        "12 grade points": "10",
        "13 credits*grade": "40",
        "14 ptr": "",
    },
    "DCSC304": {
        "0 cc": "DCSC304",
        "1 subj": "Electronic Circuits and Communication\rFundamentals",
        "2  highest": "99",
        "3 course credits": "4",
        "4 tt highest": "25",
        "5 tt marks": "21",
        "6 sem highest": "75",
        "7 sem marks": "45",
        "8 final max": "100",
        "9 marks obtained": "66",
        "10 grade": "C",
        "11 credits": "4",
        "12 grade points": "7",
        "13 credits*grade": "28",
        "14 ptr": "",
    },
    "DCSL304": {
        "0 cc": "DCSL304",
        "1 subj": "Electronics Circuits and Communication\rFundamentals Laboratory",
        "2  highest": "49",
        "3 course credits": "1",
        "4 tt highest": "25",
        "5 tt marks": "24",
        "6 sem highest": "25",
        "7 sem marks": "23",
        "8 final max": "50",
        "9 marks obtained": "47",
        "10 grade": "O",
        "11 credits": "1",
        "12 grade points": "10",
        "13 credits*grade": "10",
        "14 ptr": "",
    },
    "DCSC305": {
        "0 cc": "DCSC305",
        "1 subj": "Data Structures",
        "2  highest": "98",
        "3 course credits": "4",
        "4 tt highest": "25",
        "5 tt marks": "21",
        "6 sem highest": "75",
        "7 sem marks": "69",
        "8 final max": "100",
        "9 marks obtained": "90",
        "10 grade": "O",
        "11 credits": "4",
        "12 grade points": "10",
        "13 credits*grade": "40",
        "14 ptr": "",
    },
    "DCSL305": {
        "0 cc": "DCSL305",
        "1 subj": "Data Structures Laboratory",
        "2  highest": "47",
        "3 course credits": "1",
        "4 tt highest": "25",
        "5 tt marks": "23",
        "6 sem highest": "25",
        "7 sem marks": "24",
        "8 final max": "50",
        "9 marks obtained": "47",
        "10 grade": "O",
        "11 credits": "1",
        "12 grade points": "10",
        "13 credits*grade": "10",
        "14 ptr": "",
    },
    "DCSL306": {
        "0 cc": "DCSL306",
        "1 subj": "Object Oriented Programming Methodology\rLaboratory",
        "2  highest": "96",
        "3 course credits": "2",
        "4 tt highest": "50",
        "5 tt marks": "48",
        "6 sem highest": "50",
        "7 sem marks": "46",
        "8 final max": "100",
        "9 marks obtained": "94",
        "10 grade": "O",
        "11 credits": "2",
        "12 grade points": "10",
        "13 credits*grade": "20",
        "14 ptr": "",
    },
    "Total": {
        "0 cc": "Total",
        "1 subj": "",
        "2  highest": "26",
        "3 course credits": "",
        "4 tt highest": "",
        "5 tt marks": "",
        "6 sem highest": "",
        "7 sem marks": "",
        "8 final max": "",
        "9 marks obtained": "",
        "10 grade": "26",
        "11 credits": "",
        "12 grade points": "236",
        "13 credits*grade": "",
        "14 ptr": "",
    },
    "Remark : SuccessfulCredits Earned :26SGPA :9.08": {
        "0 cc": "Remark : SuccessfulCredits Earned :26SGPA :9.08",
        "1 subj": "",
        "2  highest": "",
        "3 course credits": "",
        "4 tt highest": "",
        "5 tt marks": "",
        "6 sem highest": "",
        "7 sem marks": "",
        "8 final max": "",
        "9 marks obtained": "",
        "10 grade": "",
        "11 credits": "",
        "12 grade points": "",
        "13 credits*grade": "",
        "14 ptr": "",
    },
    "": {
        "0 cc": "",
        "1 subj": "",
        "2  highest": "",
        "3 course credits": "",
        "4 tt highest": "",
        "5 tt marks": "",
        "6 sem highest": "",
        "7 sem marks": "",
        "8 final max": "",
        "9 marks obtained": "",
        "10 grade": "",
        "11 credits": "",
        "12 grade points": "",
        "13 credits*grade": "",
        "14 ptr": "",
    },
}


# {
#     3: {
#         "DJ19CEC301": {
#             "name": "Engineering Mathematics -III",
#             "highest": "100",
#             "course credits": "3",
#         },
#         "DJ19CET301": {
#             "name": "Engineering Mathematics –III Tutorial",
#             "highest": "24",
#             "course credits": "1",
#         },
#         "DJ19CEC302": {
#             "name": "Data Structures",
#             "highest": "97",
#             "course credits": "3",
#         },
#         "DJ19CEL302": {
#             "name": "Data Structures Laboratory",
#             "highest": "47",
#             "course credits": "1",
#         },
#         "DJ19CEC303": {
#             "name": "Discrete Structures",
#             "highest": "97",
#             "course credits": "3",
#         },
#         "DJ19CET303": {
#             "name": "Discrete Structures Tutorial",
#             "highest": "23",
#             "course credits": "1",
#         },
#         "DJ19CEC304": {
#             "name": "Database Management Systems",
#             "highest": "95",
#             "course credits": "3",
#         },
#         "DJ19CEL304": {
#             "name": "Database Management Systems Laboratory",
#             "highest": "48",
#             "course credits": "1",
#         },
#         "DJ19CEC305": {
#             "name": "Digital Electronics",
#             "highest": "92",
#             "course credits": "3",
#         },
#         "DJ19CEL305": {
#             "name": "Digital Electronics Laboratory",
#             "highest": "48",
#             "course credits": "1",
#         },
#         "DJ19CEL306": {
#             "name": "Programming Laboratory- I (Java)",
#             "highest": "97",
#             "course credits": "2",
#         },
#         "DJ19A2": {
#             "name": "Innovative Product Development I",
#             "highest": "0",
#             "course credits": "0",
#         },
#         "DJ19A3": {
#             "name": "Constitution of India",
#             "highest": "0",
#             "course credits": "0",
#         },
#     }
# }
